workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1 # machine instance type
    max_build_duration: 45

    environment:
      groups:
        - firebase_credentials

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build Android App
        script: flutter build apk --release
      - name: Get packages
        script: flutter pub get

    artifacts:
      - build/**/outputs/apk/**/*.apk # relative path
      - build/**/outputs/**/*.aab

    publishing:
      firebase:
        # use this line to authenticate via service account
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT

        android:
          # Add your Android app id retrieved from Firebase console
          app_id: x:xxxxxxxxxxxx:android:xxxxxxxxxxxxxxxxxxxxxx

          groups:
            - staging
          artifact_type: "aab" # Replace with 'aab' to only publish the Android app bundle

      email:
        recipients:
          - tam@mailinator.com
