name: pokebook
description: Pokebook app assessment
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: null
  flutter_svg_provider: null
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.4
  image: ^4.1.7
  intl: ^0.18.0
  json_annotation: ^4.8.1
  number_paginator: ^0.4.1
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  pokemon_repository:
    path: ./packages/pokemon_repository
  sentry_flutter: ^7.18.0
  firebase_core: ^2.24.2

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: null
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
