// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhFA8TTzfEmbwwfs86XVZ-lIdV1yB2UWE',
    appId: '1:50284643270:web:d45cdb9bc7e481f7dc28c7',
    messagingSenderId: '50284643270',
    projectId: 'poke-book-task',
    authDomain: 'poke-book-task.firebaseapp.com',
    storageBucket: 'poke-book-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMM-Gh7URg3GuaX6zS9LFbLQar6cEX-gM',
    appId: '1:50284643270:android:508e0de0f163e528dc28c7',
    messagingSenderId: '50284643270',
    projectId: 'poke-book-task',
    storageBucket: 'poke-book-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWmXcpjfibzyxH474nE-_u8RmP2ybCA3I',
    appId: '1:50284643270:ios:cbaf67fc708ea07cdc28c7',
    messagingSenderId: '50284643270',
    projectId: 'poke-book-task',
    storageBucket: 'poke-book-task.appspot.com',
    iosBundleId: 'com.example.verygoodcore.pokebook',
  );
}
